"""empty message

Revision ID: 3f3fe89918fe
Revises: 
Create Date: 2025-09-01 23:31:52.234526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3fe89918fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branch')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name_uz', sa.VARCHAR(length=200), nullable=True),
    sa.Column('name_ru', sa.VARCHAR(length=200), nullable=True),
    sa.Column('name_en', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description_uz', sa.TEXT(), nullable=True),
    sa.Column('description_ru', sa.TEXT(), nullable=True),
    sa.Column('description_en', sa.TEXT(), nullable=True),
    sa.Column('for_whom_uz', sa.TEXT(), nullable=True),
    sa.Column('for_whom_ru', sa.TEXT(), nullable=True),
    sa.Column('for_whom_en', sa.TEXT(), nullable=True),
    sa.Column('components_uz', sa.TEXT(), nullable=True),
    sa.Column('components_ru', sa.TEXT(), nullable=True),
    sa.Column('components_en', sa.TEXT(), nullable=True),
    sa.Column('company_uz', sa.VARCHAR(length=200), nullable=True),
    sa.Column('company_ru', sa.VARCHAR(length=200), nullable=True),
    sa.Column('company_en', sa.VARCHAR(length=200), nullable=True),
    sa.Column('usage_uz', sa.TEXT(), nullable=True),
    sa.Column('usage_ru', sa.TEXT(), nullable=True),
    sa.Column('usage_en', sa.TEXT(), nullable=True),
    sa.Column('not_usage_uz', sa.TEXT(), nullable=True),
    sa.Column('not_usage_ru', sa.TEXT(), nullable=True),
    sa.Column('not_usage_en', sa.TEXT(), nullable=True),
    sa.Column('storage_uz', sa.TEXT(), nullable=True),
    sa.Column('storage_ru', sa.TEXT(), nullable=True),
    sa.Column('storage_en', sa.TEXT(), nullable=True),
    sa.Column('expiry_uz', sa.VARCHAR(length=100), nullable=True),
    sa.Column('expiry_ru', sa.VARCHAR(length=100), nullable=True),
    sa.Column('expiry_en', sa.VARCHAR(length=100), nullable=True),
    sa.Column('certificate_uz', sa.TEXT(), nullable=True),
    sa.Column('certificate_ru', sa.TEXT(), nullable=True),
    sa.Column('certificate_en', sa.TEXT(), nullable=True),
    sa.Column('promotion_uz', sa.TEXT(), nullable=True),
    sa.Column('promotion_ru', sa.TEXT(), nullable=True),
    sa.Column('promotion_en', sa.TEXT(), nullable=True),
    sa.Column('conclusion_uz', sa.TEXT(), nullable=True),
    sa.Column('conclusion_ru', sa.TEXT(), nullable=True),
    sa.Column('conclusion_en', sa.TEXT(), nullable=True),
    sa.Column('country_uz', sa.VARCHAR(length=120), nullable=True),
    sa.Column('country_ru', sa.VARCHAR(length=120), nullable=True),
    sa.Column('country_en', sa.VARCHAR(length=120), nullable=True),
    sa.Column('location_uz', sa.VARCHAR(length=120), nullable=True),
    sa.Column('location_ru', sa.VARCHAR(length=120), nullable=True),
    sa.Column('location_en', sa.VARCHAR(length=120), nullable=True),
    sa.Column('image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('qr_code', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_scanned_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('views', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
