"""empty message

Revision ID: 4011361cd324
Revises: 
Create Date: 2025-09-14 21:56:08.005797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4011361cd324'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name_uz', sa.String(length=200), nullable=True),
    sa.Column('name_ru', sa.String(length=200), nullable=True),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('description_uz', sa.Text(), nullable=True),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('for_whom_uz', sa.Text(), nullable=True),
    sa.Column('for_whom_ru', sa.Text(), nullable=True),
    sa.Column('for_whom_en', sa.Text(), nullable=True),
    sa.Column('components_uz', sa.Text(), nullable=True),
    sa.Column('components_ru', sa.Text(), nullable=True),
    sa.Column('components_en', sa.Text(), nullable=True),
    sa.Column('company_uz', sa.String(length=200), nullable=True),
    sa.Column('company_ru', sa.String(length=200), nullable=True),
    sa.Column('company_en', sa.String(length=200), nullable=True),
    sa.Column('usage_uz', sa.Text(), nullable=True),
    sa.Column('usage_ru', sa.Text(), nullable=True),
    sa.Column('usage_en', sa.Text(), nullable=True),
    sa.Column('not_usage_uz', sa.Text(), nullable=True),
    sa.Column('not_usage_ru', sa.Text(), nullable=True),
    sa.Column('not_usage_en', sa.Text(), nullable=True),
    sa.Column('storage_uz', sa.Text(), nullable=True),
    sa.Column('storage_ru', sa.Text(), nullable=True),
    sa.Column('storage_en', sa.Text(), nullable=True),
    sa.Column('expiry_uz', sa.String(length=100), nullable=True),
    sa.Column('expiry_ru', sa.String(length=100), nullable=True),
    sa.Column('expiry_en', sa.String(length=100), nullable=True),
    sa.Column('certificate_uz', sa.Text(), nullable=True),
    sa.Column('certificate_ru', sa.Text(), nullable=True),
    sa.Column('certificate_en', sa.Text(), nullable=True),
    sa.Column('promotion_uz', sa.Text(), nullable=True),
    sa.Column('promotion_ru', sa.Text(), nullable=True),
    sa.Column('promotion_en', sa.Text(), nullable=True),
    sa.Column('conclusion_uz', sa.Text(), nullable=True),
    sa.Column('conclusion_ru', sa.Text(), nullable=True),
    sa.Column('conclusion_en', sa.Text(), nullable=True),
    sa.Column('country_uz', sa.String(length=120), nullable=True),
    sa.Column('country_ru', sa.String(length=120), nullable=True),
    sa.Column('country_en', sa.String(length=120), nullable=True),
    sa.Column('location_uz', sa.String(length=120), nullable=True),
    sa.Column('location_ru', sa.String(length=120), nullable=True),
    sa.Column('location_en', sa.String(length=120), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_views')
    op.drop_table('products')
    op.drop_table('branches')
    # ### end Alembic commands ###
