"""empty message

Revision ID: 9787c88ab0a5
Revises: 3f3fe89918fe
Create Date: 2025-09-03 10:54:40.300633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9787c88ab0a5'
down_revision = '3f3fe89918fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_view')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_view',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('lang', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
